export const enStrings = {
  queryLabel: "Research query",
  placeholder: "Person name Company name Job title",
  submit: "Run DeepResearch",
  stop: "Cancel",
  idleStatus: "",
  runningStatus: "Research in progress…",
  progressHeading: "Progress",
  progressIdle: "Run a query to start a fresh session.",
  progressComplete: "Research complete. Export it now if you want to keep it.",
  progressCancelled: "Research stopped. Showing the collected results only.",
  progressCancelledEmpty: "Research stopped before any evidence was collected.",
  sessionTitle: "Temporary session",
  sessionBody: "Results are not stored. Refreshing or closing this page starts over.",
  sessionHint: "Need to keep the output? Export Word or Markdown before leaving this page.",
  planHeading: "Research plan",
  planExpectation: "",
  planEmpty: "No plan yet. Start a run to generate the investigation steps.",
  evidenceHeading: "Evidence digests",
  evidenceEmpty: "Evidence will appear here as the agent completes each step.",
  reportHeading: "Final report",
  reportEmpty: "Run DeepResearch to produce a final report.",
  sourcesHeading: "References",
  sourcesEmpty: "References will be listed once the run finishes.",
  errorLabel: "Error",
  imagesHeading: "Likely subject photos",
  imagesLoading: "Fetching images…",
  imagesEmpty: "Images will appear here after DeepResearch starts.",
  imagesNotFound: "No images found for this subject.",
  exportWord: "Export to Word",
  exportMarkdown: "Export to Markdown",
  stepStatusPending: "Pending",
  stepStatusRunning: "Running",
  stepStatusCompleted: "Completed",
  stepStatusPartial: "Partial",
  stepStatusFailed: "Failed",
  stepStatusCancelled: "Cancelled",
} as const;

export const jaStrings = {
  queryLabel: "調査したい内容",
  placeholder: "調査対象者名 会社名 役職名",
  submit: "DeepResearch を実行",
  stop: "中止",
  idleStatus: "",
  runningStatus: "調査を実行中…",
  progressHeading: "進捗",
  progressIdle: "クエリを実行すると新しい一時セッションが始まります。",
  progressComplete: "調査が完了しました。残したい場合はすぐにエクスポートしてください。",
  progressCancelled: "調査を中断しました。収集済みの結果のみ表示しています。",
  progressCancelledEmpty: "エビデンス収集前に調査を中断しました。",
  sessionTitle: "一時セッション",
  sessionBody: "結果は保存されません。ページを再読み込みまたは閉じると最初からやり直しになります。",
  sessionHint: "結果を残したい場合は、このページを離れる前に Word か Markdown で出力してください。",
  planHeading: "調査プラン",
  planExpectation: "",
  planEmpty: "まだプランはありません。調査を実行するとステップが表示されます。",
  evidenceHeading: "エビデンス概要",
  evidenceEmpty: "各ステップの完了とともにエビデンスが表示されます。",
  reportHeading: "最終レポート",
  reportEmpty: "調査を実行すると最終レポートがここに表示されます。",
  sourcesHeading: "参照元",
  sourcesEmpty: "調査完了後に参照元リンクが表示されます。",
  errorLabel: "エラー",
  imagesHeading: "想定される対象者の写真",
  imagesLoading: "画像を取得しています…",
  imagesEmpty: "調査を実行するとここに画像候補が表示されます。",
  imagesNotFound: "該当する画像は見つかりませんでした。",
  exportWord: "Wordで出力",
  exportMarkdown: "Markdownで出力",
  stepStatusPending: "待機中",
  stepStatusRunning: "実行中",
  stepStatusCompleted: "完了",
  stepStatusPartial: "部分的",
  stepStatusFailed: "失敗",
  stepStatusCancelled: "中断済み",
} as const;

export type DeepResearchUiStrings = typeof enStrings;
